### ISSUE TITLE
UI customisation: is there any way by which we can change look of camera screen  

### ISSUE THREAD

**Issue by dhavalSA** [DFTinc/onyx-ios-cocoapod-example#2]
for example i want to remove hand logo from bottom .  i am attaching screenshot for better understanding .
[
![IMG_64D132C48FFF-1](https://user-images.githubusercontent.com/62322557/94552755-013aec00-0275-11eb-871d-19187777dbe3.jpeg)
](url)

**Comment by Chacemanhattan** [comment]
You're not permitted to remove the logo, as a part of your license you have
to maintain the marketing of ONYX.
