### ISSUE TITLE
Setting camera layout for left hand & Right hand not working 

### ISSUE THREAD

**Issue by dhavalSA** [DFTinc/onyx-ios-cocoapod-example#4]
i want to scan Left hand finder and then Right hand finger separately, but configuring camera screen for the same is not working . i am using following config.
onyxConfigBuilder.onyxConfig.reticleOrientation = RIGHT
onyxConfigBuilder.onyxConfig.reticleOrientation = LEFT 
this configuration have no effect in camera layout

**Comment by Chacemanhattan** [comment]
Apologies that's actually a deprecated method from the previous single
finger capture version it has no effect in the current four finger calture
UI (6.x.x and newer).

**Comment by dhavalSA** [comment]
is there any way by which we can identify that scanned finger are right hand finger or left hand finger

**Comment by Chacemanhattan** [comment]
you can getSide from CaptureNetOutputs

**Comment by dhavalSA** [comment]
in success call back i am getting array of OnyxResult , how to get CaptureNetOutputs , can you please share document or sample code

**Comment by Chacemanhattan** [comment]
In your OnyxResult View Header file:

`@property NSString* side;`

and in your OnyxResult View file:

`_side = [[_onyxResult getMetrics] side];
    NSLog(@"Hand Side: %@", _side);`
